import Layout from '@/ui/site/Layout';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import './global.css';

export const metadata = {
  title: 'Welcome to temp',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Layout>{children}</Layout>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
