grid-rows: 1
onboardLanding: {
  shape: page
  grid-rows: 4
  addOnboardingPatient
  importPatients
  searchPatient: {
    filter: {
      facility
      rtQualified
      rtStatus
    }
  }
  searchResults: {
    grid-rows: 1
    name
    facility
    rtProgress: {
      grid-columns: 1
      status
      qualified
      nextAction
    }
    notifications: {
      grid-columns: 1
      rt
      nurse
      admin
      don
      mngr
    }
    ehr: {
      view
    }
    actions: {
      delete
      edit
    }
  }
  pageResultNavigation: {
    grid-rows: 1
    first
    previous
    pageNumbers
    next
    last
  }
}

createPatient: {
  label.near: top-center
  shape: page
  searchPatient: {
    grid-rows: 3
    facility: {
      width: 300
    }
    firstName: {
      width: 100
    }
    lastName: {
      width: 100
    }
    dob: {
      width: 100
    }
    patientId: {
      width: 150
    }
    search: {
      width: 150
    }
  }
  searchResults: {
    grid-rows: 1
    name
    facility
    dob
    startOnboarding
  }
}
createAdmission: {
  height: 1
  confirm
  cancel
}
onboardingLoading: {
  grid-rows: 3
  header: {
    grid-rows: 1
    viewHistory
    savePatient
  }
  onBoardingProgress: {
    grid-rows: 1
    initiatedOnboarding
    ehrRecordSync
    notificationsSent
    rtReview
    qualificationCheck
    residentStatus
    *.shape: step
  }
  details: {
    grid-columns: 2
    onBoardingProgress: {
      tabs: {
        grid-rows: 1
        notifications
        rtReview
        qualCheck
        qualDocuments
      }
      qualityCheck: {
        header: {
          grid-rows: 1
          diagnosis
          evidence
          dateRecorded
          status
        }
      }
    }
    ehr: {
      grid-rows: 3
      refreshEhr
      patientName
      details: {
        dob
        facility
        patientId
        gender
        patientStatus
        condition
        medication
        observation
      }
    }
  }
}

onboardLanding.addOnboardingPatient -> createPatient
createPatient.searchResults.startOnboarding -> createAdmission
