grid-rows: 1
onboardLanding: {
  shape: page
  grid-rows: 4
  addOnboardingPatient
  importPatients
  searchPatient: {
    filter: {
      facility
      rtQualified
      rtStatus
    }
  }
  searchResults: {
    grid-rows: 1
    name
    facility
    rtProgress: {
      grid-columns: 1
      status
      qualified
      nextAction
    }
    notifications: {
      grid-columns: 1
      rt
      nurse
      admin
      don
      mngr
    }
    ehr: {
      view
    }
    actions: {
      delete
      edit
    }
  }
  pageResultNavigation: {
    grid-rows: 1
    first
    previous
    pageNumbers
    next
    last
  }
}

createPatient: {
  label.near: top-center
  shape: page
  searchPatient: {
    grid-rows: 3
    facility: {
      width: 300
    }
    firstName: {
      width: 100
    }
    lastName: {
      width: 100
    }
    dob: {
      width: 100
    }
    patientId: {
      width: 150
    }
    search: {
      width: 150
    }
  }
  searchResults: {
    grid-rows: 1
    name
    facility
    dob
    startOnboarding
  }
}
createAdmission: {
  height: 1
  confirm
  cancel
}
onboardingLoading: {
  grid-rows: 3
  header: {
    grid-rows: 1
    viewHistory
    savePatient
  }
  onBoardingStatus: {
    grid-rows: 1
    initiatedOnboarding
    ehrSync
    notifications
    rtReview
    qualificationCheck
    deviceFit
    *.shape: step
  }
  details: {
    grid-columns: 2
    onBoardingStatus: {
      tabs: {
        grid-rows: 1
        ehrData
        notifications
        rtReview
        qualificationCheck
        deviceFit
      }
      ehrData: {
        EHR Sync in Progress
      }
    }
    ehr: {
      circularProgress
    }
  }
}

onboardingStep1: {
  grid-rows: 3
  header: {
    grid-rows: 1
    viewHistory
    saveProgess
  }
  onBoardingStatus: {
    grid-rows: 1
    initiatedOnboarding
    ehrSync
    notifications
    rtReview
    qualificationCheck
    deviceFit
    *.shape: step
  }
  details: {
    grid-columns: 2
    onBoardingStatus: {
      tabs: {
        grid-rows: 1
        ehrData
        notifications
        rtReview
        qualificationCheck
        deviceFit
      }
      ehrData: {
        grid-rows: 1
        diagnosis
        status
        evidence
        dateRecorded
        medicare
      }
    }
    ehr: {
      grid-rows: 3
      patientName
      details: {
        dob
        facility
        patientId
        gender
        patientStatus
        condition
        medication
        observation
      }
    }
  }
}
onboardingStep2: {
  grid-rows: 3
  header: {
    grid-rows: 1
    viewHistory
    saveProgess
  }
  onBoardingStatus: {
    grid-rows: 1
    initiatedOnboarding
    ehrSync
    notifications
    rtReview
    qualificationCheck
    deviceFit
    *.shape: step
  }
  details: {
    grid-columns: 2
    onBoardingStatus: {
      tabs: {
        grid-rows: 1
        ehrData
        notifications
        rtReview
        qualificationCheck
        deviceFit
      }
      notifications: {
        grid-rows: 1
        notified
        recipientName
        email
        emailStatus
        status: {
          actions
        }
      }
    }
    ehr: {
      grid-rows: 3
      patientName
      details: {
        dob
        facility
        patientId
        gender
        patientStatus
        condition
        medication
        observation
      }
    }
  }
}
onboardingStep3: {
  grid-rows: 3
  header: {
    grid-rows: 1
    viewHistory
    saveProgess
  }
  onBoardingStatus: {
    grid-rows: 1
    initiatedOnboarding
    ehrSync
    notifications
    rtReview
    qualificationCheck
    deviceFit
    *.shape: step
  }
  details: {
    grid-columns: 2
    onBoardingStatus: {
      tabs: {
        grid-rows: 1
        ehrData
        notifications
        rtReview
        qualificationCheck
        deviceFit
      }
      rtReview: {
        grid-rows: 1
        complianceStandard
        ub04Section
        sourceDocument
        standardMet: {
          initialHere
        }
      }
    }
    ehr: {
      grid-rows: 3
      patientName
      details: {
        dob
        facility
        patientId
        gender
        patientStatus
        condition
        medication
        observation
      }
    }
  }
}

onboardLanding.addOnboardingPatient -> createPatient
createPatient.searchResults.startOnboarding -> createAdmission
